services:
  video-api:
    build: ./video-api
    container_name: video_api
    environment:
      - STORAGE_ENDPOINT=http://minio:9000
      - STORAGE_BUCKET=${S3_BUCKET_NAME}
      - STORAGE_ACCESS_KEY=${S3_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${S3_SECRET_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./video-api:/app
      - ./storage/output:/app/output
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
    networks:
      - pipe-network

  video-worker:
    build: ./video-worker
    container_name: video_worker
    environment:
      - STORAGE_ENDPOINT=http://minio:9000
      - STORAGE_BUCKET=${S3_BUCKET_NAME}
      - STORAGE_ACCESS_KEY=${S3_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${S3_SECRET_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./video-worker:/app
      - ./storage/output:/app/output
    depends_on:
      - video-api
      - redis
    networks:
      - pipe-network

  redis:
    image: redis:7-alpine
    container_name: video_redis
    networks:
      - pipe-network

  minio:
    image: minio/minio
    container_name: minio_storage
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - pipe-network

networks:
  pipe-network:
    external: true

volumes:
  minio_data: